/*
 *Triangle, square, pentagonal, hexagonal, heptagonal, and octagonal numbers
 *are all figurate (polygonal) numbers and are generated by the following formulae:
 *
 * Triangle	 	    P(3,n)=n(n+1)/2	 	    1, 3, 6, 10, 15, ...
 * Square	 	    P(4,n)=n^2	 	        1, 4, 9, 16, 25, ...
 * Pentagonal	 	P(5,n)=n(3n−1)/2	    1, 5, 12, 22, 35, ...
 * Hexagonal	 	P(6,n)=n(2n−1)	 	    1, 6, 15, 28, 45, ...
 * Heptagonal	 	P(7,n)=n(5n−3)/2	    1, 7, 18, 34, 55, ...
 * Octagonal	 	P(8,n)=n(3n−2)	 	    1, 8, 21, 40, 65, ...
 * 
 *The ordered set of three 4-digit numbers: 8128, 2882, 8281, has three interesting properties.
 * 1. The set is cyclic, in that the last two digits of each number is the first two digits
 * of the next number (including the last number with the first).
 * 2. Each polygonal type: triangle (P(3,127)=8128), square (P(4,91)=8281),
 * and pentagonal (P(5,44)=2882), is represented by a different number in the set.
 * 3. This is the only set of 4-digit numbers with this property.
 *Find the sum of the only ordered set of six cyclic 4-digit numbers for which each
 *polygonal type: triangle, square, pentagonal, hexagonal, heptagonal, and octagonal,
 *is represented by a different number in the set.
*/

#include <stdio.h>

int     triangle(int n)
{
    return (n * (n + 1) / 2);
}

int     square(int n)
{
    return (n * n);
}

int     pentagonal(int n)
{
    return (n * (3 * n - 1) / 2);
}

int     hexagonal(int n)
{
    return (n * (2 * n - 1));
}

int     heptagonal(int n)
{
    return (n * (5 * n - 3) / 2);
}

int     octagonal(int n)
{
    return (n * (3 * n - 2));
}

int     capacityCount(int numb)
{
    int capacity;

    capacity = 1;
    while (numb / 10 > 0)
    {
        capacity++;
        numb = numb / 10;
    }
    return (capacity);
}

int     isCyclic(int *arr, int len)
{
    int cycCount, i, j;
    
    cycCount = 0;
    i = 0;
    while (i < len)
    {
        j = 0;
        while (j < len)
        {
            if (arr[i] / 100 == arr[j] % 100 && i != j && arr[j] / 100 != arr[i] % 100)
                cycCount++;
            if ((arr[i] / 100 == arr[j] / 100 || arr[i] % 100 == arr[j] % 100) && i != j)
                return (0);
            j++;
        }
        i++;
    }
    if (cycCount == len)
        return (1);
    else
        return (0);
}

void    fillArr(int *arr,int func(int))
{
    int n, i;

    n = 1;
    i = 0;
    while (i < 100)
    {
        if (capacityCount(func(n)) == 4)
        {
            arr[i] = func(n);
            i++;
        }
        n++;
    }
}

int     findElements(int matrix[][100], int *arr)
{
    int i, tr, sq, pn, hx, hp, oc, sum;

    i = 0;
    tr = 0;
    sq = 0;
    pn = 0;
    hx = 0;
    hp = 0;
    oc = 0;
    sum = 0;
    while (!isCyclic(arr, 6))
    {
        tr++;
        if (tr == 100 || capacityCount(matrix[0][tr]) != 4)
        {
            tr = 0;
            arr[0] = matrix[0][tr];
            sq++;
            arr[1] = matrix[1][sq];
        }
        if (sq == 100 || capacityCount(matrix[1][sq]) != 4)
        {
            sq = 0;
            arr[1] = matrix[1][sq];
            pn++;
            arr[2] = matrix[2][pn];
        }
        if (pn == 100 || capacityCount(matrix[2][pn]) != 4)
        {
            pn = 0;
            arr[2] = matrix[2][pn];
            hx++;
            arr[3] = matrix[3][hx];
        }
        if (hx == 100 || capacityCount(matrix[3][hx]) != 4)
        {
            hx = 0;
            arr[3] = matrix[3][hx];
            hp++;
            arr[4] = matrix[4][hp];
        }
        if (hp == 100 || capacityCount(matrix[4][hp]) != 4)
        {
            hp = 0;
            arr[4] = matrix[4][hp];
            oc++;
            arr[5] = matrix[5][oc];
        }
        if (oc == 100 || capacityCount(matrix[5][oc]) != 4)
        {
            printf("not found");
            return (0);
        }
        arr[0] = matrix[0][tr];
    }
    i = 0;
    while (i < 6)
    {
        sum += arr[i];
        printf("%d ", arr[i]);
        i++;
    }
    return (sum);
}

int     main()
{
    int matrix[6][100], cyclicArr[6];
    int i;

    i = 0;
    fillArr(matrix[0], triangle);
    fillArr(matrix[1], square);
    fillArr(matrix[2], pentagonal);
    fillArr(matrix[3], hexagonal);
    fillArr(matrix[4], heptagonal);
    fillArr(matrix[5], octagonal);
    while (i < 6)
    {
        cyclicArr[i] = matrix[i][0];
        i++;
    }
    printf("\n%d\n", findElements(matrix, cyclicArr));
    return (0);
}