/*
 * Each new term in the Fibonacci sequence is generated by adding the previous two terms.
 * By starting with 1 and 2, the first 10 terms will be:
 * 1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...
 * By considering the terms in the Fibonacci sequence whose values do not exceed four million, find the sum of the even-valued terms.
*/

#include <stdio.h>

int	main(void)
{
	int	fib, l0, l1, sum;
	
	l0 = 1;
	l1 = 2;
	sum = 2;
	fib = 0;
	while (fib < 4000000)
	{
		fib = l0 + l1;
		l0 = l1;
		l1 = fib;
		if ((fib % 2) == 0)
			sum = sum + fib;
	}
	printf("%d\n", sum);
}
